"""empty message

Revision ID: 24528dfa718b
Revises: 9c6d6d90485
Create Date: 2015-10-12 16:09:59.620862

"""

# revision identifiers, used by Alembic.
revision = '24528dfa718b'
down_revision = '9c6d6d90485'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('type', sa.Enum('Full Time', 'Part Time', 'Others', 'Ignore', name='plan_types'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'type')
    ### end Alembic commands ###
