"""empty message

Revision ID: 9c6d6d90485
Revises: None
Create Date: 2015-10-12 14:57:29.377761

"""

# revision identifiers, used by Alembic.
revision = '9c6d6d90485'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_date'), 'time', ['date'], unique=False)
    op.create_table('member_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('hub_plan_id', sa.Integer(), nullable=True),
    sa.Column('new_member_count', sa.Integer(), nullable=True),
    sa.Column('retain_member_count', sa.Integer(), nullable=True),
    sa.Column('leave_member_count', sa.Integer(), nullable=True),
    sa.Column('new_member_revenue', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('retain_member_revenue', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('leave_member_revenue', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['hub_plan_id'], ['hub_plan.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_report')
    op.drop_index(op.f('ix_time_date'), table_name='time')
    op.drop_table('time')
    ### end Alembic commands ###
